import type { Clinic } from '../types/clinic';

export const MOCK_CLINICS: Clinic[] = [
  {
    id: '3r',
    name: '3r',
    address: 'Praha 3, Korunní 79',
    email: 'info@3rsro.cz',
    phone: '+420224253455',
    website: 'http://www.3rsro.cz/',
    photoUrl: 'https://firebasestorage.googleapis.com/v0/b/zoryx-d58dc.appspot.com/o/%D1%80%D0%B5%D1%85%D0%B0%D0%B1%202.png?alt=media&token=e202f72c-dca8-4d8f-bbc8-c16e72a0ebca',
    rank: 3800,
    languages: ['cs', 'en'],
    specializations: ['Rehabilitace a fyzioterapie'],
    insurances: 'VZP – 111, VoZP – 201, ČPZP – 205, OZP – 207, ZP MV ČR – 211, RBP – 213',
    updatedAt: '10/7/2025',
    info: {
      cs: 'Rehabilitační studio 3R poskytuje služby fyzioterapie a rehabilitace zaměřené na zlepšení tělesné a psychické kondice klientů. Nabízí relaxační a léčebné procedury, včetně masáží, lymfodrenáže, rašeliny, léčebných technik, LTV a fyzikální terapie.',
      en: 'Rehabilitation Studio 3R provides physiotherapy and rehabilitation services focused on improving clients\' physical and mental condition. It offers relaxation and therapeutic procedures including massages, lymphatic drainage, peat therapy, therapeutic techniques, LTV, and physical therapy.',
      ru: 'Реабилитационная студия 3R предоставляет услуги физиотерапии и реабилитации, направленные на улучшение физического и психического состояния клиентов.',
      uk: 'Реабілітаційна студія 3R надає послуги фізіотерапії та реабілітації, спрямовані на покращення фізичного та психічного стану клієнтів.',
    },
  },
  {
    id: 'AlphaLabs',
    name: 'Alphalabs',
    address: 'Praha 7, Bubenské nábřeží 1594/6',
    email: 'info@alphalabs.cz',
    phone: '+420910920819',
    website: 'https://www.alphalabs.cz/o-nas#kontakt',
    photoUrl: 'https://firebasestorage.googleapis.com/v0/b/zoryx-d58dc.appspot.com/o/clinics%2F1766245286241_%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%8F%202.png?alt=media&token=b9f41ed1-b138-4134-9fda-599d840bce1b',
    rank: 1800,
    languages: ['cs', 'en'],
    specializations: ['Laboratory'],
    insurances: 'find out by email',
    updatedAt: '12/20/2025',
    info: {
      cs: 'Klinika ALPHALABS nabízí nejmodernější testosteronovou terapii, která je nejrozšířenější a nejefektivnější metodou doplnění testosteronu. Terapie pomáhá obnovit fyzickou i psychickou sílu.',
      en: 'ALPHALABS Clinic offers the most modern testosterone therapy, the most widespread and effective method of testosterone supplementation. The therapy helps restore both physical and mental strength.',
      ru: 'Клиника ALPHALABS предлагает самую современную терапию тестостероном, которая является наиболее распространенным и эффективным методом восполнения тестостерона.',
      uk: 'Клініка ALPHALABS пропонує найсучаснішу терапію тестостероном, найпоширенішу та найефективнішу методику доповнення тестостерону.',
    },
  },
  {
    id: 'Amfion',
    name: 'Amfion Dezinfekční Stanice',
    address: 'Praha 7, Strojnická 999/11',
    email: 'amfion@amfion.cz',
    phone: '+420272917557',
    website: 'https://amfion.cz/amfion/kontakt/',
    photoUrl: 'https://firebasestorage.googleapis.com/v0/b/zoryx-d58dc.appspot.com/o/clinics%2F1766309884989_%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%8F%202.png?alt=media&token=eab7e0a4-84ec-43d6-a52d-c92c545c6069',
    rank: 1800,
    languages: ['cs'],
    specializations: ['Laboratory'],
    insurances: 'find out by email',
    updatedAt: '12/21/2025',
    info: {
      cs: 'Naše společnost zajišťuje infekční a neinfekční převozy pacientů především na území hlavního města Prahy od roku 2008.',
      en: 'Since 2008, our company has been providing infectious and non-infectious patient transport primarily within the city of Prague.',
      ru: 'С 2008 года наша компания занимается инфекционными и неинфекционными перевозками пациентов, в основном на территории столицы Праги.',
      uk: 'З 2008 року наша компанія займається інфекційними та неінфекційними перевезеннями пацієнтів переважно на території столиці Праги.',
    },
  },
  {
    id: 'Fresenius',
    name: 'Fresenius Medical Care DS',
    address: 'Praha 6, Evropská 423/178',
    email: 'fme.cz@freseniusmedicalcare.com',
    phone: '+420273037900',
    website: 'https://freseniusmedicalcare.com/cs-cz/kontakty/',
    rank: 3100,
    languages: ['cs', 'en'],
    specializations: ['Nefrologie'],
    insurances: 'find out by email',
    updatedAt: '12/21/2025',
    info: {
      cs: 'Program je určen pacientům s chronickým onemocněním ledvin (CKD) a jejich rodinám a poskytuje informace o možnostech léčby a života s tímto onemocněním.',
      en: 'The program is intended for patients with chronic kidney disease (CKD) and their families and provides information about treatment options and living with the condition.',
      ru: 'Программа предназначена для пациентов с хронической болезнью почек (CKD) и их семей и предоставляет информацию о возможностях лечения.',
      uk: 'Програма призначена для пацієнтів із хронічною хворобою нирок (CKD) та їхніх родин і надає інформацію про можливості лікування.',
    },
  },
];
