import type { Clinic } from '../types/clinic';

export const MOCK_CLINICS: Clinic[] = [
  {
    id: 'canadian-medical',
    name: 'Canadian Medical Care',
    address: 'Veleslavínská 1, Praha 6',
    phone: '+420 235 360 133',
    email: 'info@cmc.cz',
    website: 'https://www.cmc.cz',
    rank: 95,
    languages: ['en', 'cs', 'ru'],
    specializations: ['Cardiology', 'Gynaecology', 'Pediatrics', 'Neurology', 'Dermatology'],
    insurances: 'VZP, OZP, ZPMV, ČPZP, Foreigners insurance',
    updatedAt: '1/1/2025',
    info: {
      en: '<p>Canadian Medical Care is one of Prague\'s leading international clinics. We offer a full range of medical services for expats and Czech patients alike, with English-speaking staff available at all times.</p>',
      ru: '<p>Canadian Medical Care — одна из ведущих международных клиник Праги. Мы предлагаем полный спектр медицинских услуг для экспатов и чешских пациентов, англоговорящий персонал доступен в любое время.</p>',
      cs: '<p>Canadian Medical Care je jednou z předních mezinárodních klinik v Praze. Nabízíme plný rozsah zdravotních služeb pro cizince i české pacienty.</p>',
    },
  },
  {
    id: 'nemocnice-na-homolce',
    name: 'Nemocnice Na Homolce',
    address: 'Roentgenova 2, Praha 5',
    phone: '+420 257 271 111',
    email: 'info@homolka.cz',
    website: 'https://www.homolka.cz',
    rank: 88,
    languages: ['en', 'cs', 'de'],
    specializations: ['Neurosurgery', 'Cardiology', 'MRI', 'Oncology', 'Orthopaedics'],
    insurances: 'VZP, OZP, ZPMV, ČPZP, Foreigners insurance',
    updatedAt: '1/1/2025',
    info: {
      en: '<p>Na Homolce Hospital is a modern hospital in Prague 5, known for its neurosurgery and cardiology departments. It is one of the few hospitals in the Czech Republic with JCI accreditation.</p>',
      cs: '<p>Nemocnice Na Homolce je moderní nemocnice v Praze 5, známá svými odděleními neurochirurgie a kardiologie.</p>',
    },
  },
  {
    id: 'medicover',
    name: 'Medicover',
    address: 'Tylovo náměstí 3, Praha 2',
    phone: '+420 234 033 000',
    email: 'info@medicover.cz',
    website: 'https://www.medicover.cz',
    rank: 82,
    languages: ['en', 'cs', 'ru', 'uk'],
    specializations: ['Allergology', 'Dermatology', 'Gynaecology', 'Pediatrics', 'Cardiology', 'Dental hygiene'],
    insurances: 'VZP, OZP, Foreigners insurance',
    updatedAt: '1/1/2025',
    altegioCompanyId: 'medicover-demo',
    info: {
      en: '<p>Medicover is an international healthcare provider offering a wide range of specialist and primary care services. With multilingual staff, we are the ideal choice for Prague\'s international community.</p>',
      ru: '<p>Medicover — международный провайдер медицинских услуг с широким спектром специализированной и первичной помощи. Многоязычный персонал готов помочь на русском и украинском языках.</p>',
    },
  },
  {
    id: 'poliklinika-palladium',
    name: 'Poliklinika Palladium',
    address: 'Na Příkopě 24, Praha 1',
    phone: '+420 221 451 111',
    email: 'info@poliklinika-palladium.cz',
    website: 'https://www.poliklinika-palladium.cz',
    rank: 74,
    languages: ['en', 'cs'],
    specializations: ['Ophthalmology', 'Orthopaedics', 'Dermatology', 'Gynaecology', 'Laboratory'],
    insurances: 'VZP, OZP, ZPMV',
    updatedAt: '1/1/2025',
    info: {
      en: '<p>Poliklinika Palladium is located in the heart of Prague 1, offering convenient access to a range of specialist medical services. Our English-speaking reception staff will help you navigate your visit.</p>',
    },
  },
  {
    id: 'reprofit',
    name: 'Reprofit International',
    address: 'Hlinky 122, Brno',
    phone: '+420 543 211 880',
    email: 'info@reprofit.cz',
    website: 'https://www.reprofit.cz',
    rank: 70,
    languages: ['en', 'cs', 'ru', 'uk'],
    specializations: ['Gynaecology', 'Genetics', 'Endocrinology'],
    insurances: 'Self-pay, Foreigners insurance',
    updatedAt: '1/1/2025',
    info: {
      en: '<p>Reprofit International is a leading fertility clinic in the Czech Republic. We offer IVF, egg donation, and a full range of reproductive medicine services to patients from around the world.</p>',
      ru: '<p>Reprofit International — ведущая клиника репродуктивной медицины в Чехии. Мы предлагаем ЭКО, донорство яйцеклеток и полный спектр услуг по вспомогательным репродуктивным технологиям.</p>',
    },
  },
];
